<?php

namespace Proxies\__CG__\MyApp\ApBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Production extends \MyApp\ApBundle\Entity\Production implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPeriod($period)
    {
        $this->__load();
        return parent::setPeriod($period);
    }

    public function getPeriod()
    {
        $this->__load();
        return parent::getPeriod();
    }

    public function setPrevisionHeureD($previsionHeureD)
    {
        $this->__load();
        return parent::setPrevisionHeureD($previsionHeureD);
    }

    public function getPrevisionHeureD()
    {
        $this->__load();
        return parent::getPrevisionHeureD();
    }

    public function setPrevisionHeureF($previsionHeureF)
    {
        $this->__load();
        return parent::setPrevisionHeureF($previsionHeureF);
    }

    public function getPrevisionHeureF()
    {
        $this->__load();
        return parent::getPrevisionHeureF();
    }

    public function setHeureD($heureD)
    {
        $this->__load();
        return parent::setHeureD($heureD);
    }

    public function getHeureD()
    {
        $this->__load();
        return parent::getHeureD();
    }

    public function setHeureF($heureF)
    {
        $this->__load();
        return parent::setHeureF($heureF);
    }

    public function getHeureF()
    {
        $this->__load();
        return parent::getHeureF();
    }

    public function setClient(\MyApp\ApBundle\Entity\Client $client)
    {
        $this->__load();
        return parent::setClient($client);
    }

    public function getClient()
    {
        $this->__load();
        return parent::getClient();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setUpdated($updated)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setSatisfaction(\MyApp\ApBundle\Entity\Satisfaction $satisfaction)
    {
        $this->__load();
        return parent::setSatisfaction($satisfaction);
    }

    public function getSatisfaction()
    {
        $this->__load();
        return parent::getSatisfaction();
    }

    public function setPrevisionDateProd($previsionDateProd)
    {
        $this->__load();
        return parent::setPrevisionDateProd($previsionDateProd);
    }

    public function getPrevisionDateProd()
    {
        $this->__load();
        return parent::getPrevisionDateProd();
    }

    public function setStatut($statut)
    {
        $this->__load();
        return parent::setStatut($statut);
    }

    public function getStatut()
    {
        $this->__load();
        return parent::getStatut();
    }

    public function setNote($note)
    {
        $this->__load();
        return parent::setNote($note);
    }

    public function getNote()
    {
        $this->__load();
        return parent::getNote();
    }

    public function setNumeroContrat($numeroContrat)
    {
        $this->__load();
        return parent::setNumeroContrat($numeroContrat);
    }

    public function getNumeroContrat()
    {
        $this->__load();
        return parent::getNumeroContrat();
    }

    public function addComptabilite(\MyApp\ApBundle\Entity\Comptabilite $comptabilite)
    {
        $this->__load();
        return parent::addComptabilite($comptabilite);
    }

    public function getComptabilite()
    {
        $this->__load();
        return parent::getComptabilite();
    }

    public function addTravailleur(\MyApp\ApBundle\Entity\Travailleur $travailleur)
    {
        $this->__load();
        return parent::addTravailleur($travailleur);
    }

    public function getTravailleur()
    {
        $this->__load();
        return parent::getTravailleur();
    }

    public function setDateProd($dateProd)
    {
        $this->__load();
        return parent::setDateProd($dateProd);
    }

    public function getDateProd()
    {
        $this->__load();
        return parent::getDateProd();
    }

    public function setSatisfactionEquipe(\MyApp\ApBundle\Entity\SatisfactionEquipe $satisfactionEquipe)
    {
        $this->__load();
        return parent::setSatisfactionEquipe($satisfactionEquipe);
    }

    public function getSatisfactionEquipe()
    {
        $this->__load();
        return parent::getSatisfactionEquipe();
    }

    public function setDateTable(\MyApp\ApBundle\Entity\DateTable $dateTable)
    {
        $this->__load();
        return parent::setDateTable($dateTable);
    }

    public function getDateTable()
    {
        $this->__load();
        return parent::getDateTable();
    }

    public function addStartStop(\MyApp\ApBundle\Entity\StartStop $startStop)
    {
        $this->__load();
        return parent::addStartStop($startStop);
    }

    public function getStartStop()
    {
        $this->__load();
        return parent::getStartStop();
    }

    public function setContratCree($contratCree)
    {
        $this->__load();
        return parent::setContratCree($contratCree);
    }

    public function getContratCree()
    {
        $this->__load();
        return parent::getContratCree();
    }

    public function removeStartStop(\MyApp\ApBundle\Entity\StartStop $startStop)
    {
        $this->__load();
        return parent::removeStartStop($startStop);
    }

    public function removeComptabilite(\MyApp\ApBundle\Entity\Comptabilite $comptabilite)
    {
        $this->__load();
        return parent::removeComptabilite($comptabilite);
    }

    public function removeTravailleur(\MyApp\ApBundle\Entity\Travailleur $travailleur)
    {
        $this->__load();
        return parent::removeTravailleur($travailleur);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'period', 'previsionDateProd', 'statut', 'dateProd', 'previsionHeureD', 'previsionHeureF', 'heureD', 'heureF', 'contratCree', 'created', 'updated', 'note', 'startStop', 'client', 'satisfaction', 'satisfactionEquipe', 'dateTable', 'comptabilite', 'travailleur');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}