<?php

namespace MyApp\ApBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratRepository extends EntityRepository
{
    
  public function getAllEstimationsFranchiseCount($user)
  {
    $qb = $this->createQueryBuilder('a')
                      ->select('COUNT(a.id)')
                      ->join('a.clientService','cs')
                      ->join('cs.client','cl')
                      ->where("cl.user LIKE :user ")
                      ->setParameter('user', $user)    
                      ->orderBy('a.id', 'DESC');

        $qb = $this->whereCurrentMonth($qb);

        return $qb->getQuery()
                  ->getResult();
  }


public function whereCurrentYear(\Doctrine\ORM\QueryBuilder $qb)
{
  $qb->andWhere('a.created BETWEEN :debut AND :fin')
      ->setParameter('debut', new \Datetime(date('Y').'-01-01'))  
      ->setParameter('fin',   new \Datetime(date('Y').'-12-31')); 
 
    return $qb;
}

public function whereCurrentWeek(\Doctrine\ORM\QueryBuilder $qb)
{
  $qb->andWhere('a.created BETWEEN :debut AND :fin')
      ->setParameter('debut', new \Datetime(date('Y-m-d', strtotime("-7 days"))))
      ->setParameter('fin',   new \Datetime(date('Y').'-12-31'));
 
    return $qb;
}

public function whereCurrentMonth(\Doctrine\ORM\QueryBuilder $qb)
{
  $qb->andWhere('a.created BETWEEN :debut AND :fin')
      ->setParameter('debut', new \Datetime(date('Y-m-d', strtotime("-30 days")))) 
      ->setParameter('fin',   new \Datetime(date('Y').'-12-31')); 
 
    return $qb;
}
}



