<?php

namespace MyApp\ApBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifSemaineRepository extends EntityRepository
{
    
public function getObjectifProdByFranchise($userId, $year=null)
  {
$qb = $this->createQueryBuilder('a')
->select('a','c')
				->join('a.objectif', 'c')
				->where('a.year LIKE :year')
				->andWhere('c.utilisateur = :user')
				->setParameters(array(
					    'user' => $userId,
					    'year'  => $year,
					))
                ->orderBy('a.id', 'DESC');


    return $qb->getQuery()
              ->getResult();
  }
  public function getObjectifProdByFranchiseWeek($userId, $week=null)
  {
$qb = $this->createQueryBuilder('a')
				->join('a.objectif', 'c')
				->where('a.id LIKE :week')
				->andWhere('c.utilisateur = :user')
				->setParameters(array(
					    'user' => $userId,
					    'week'  => $week,
					))
                ->orderBy('a.id', 'DESC');


    return $qb->getQuery()
              ->getResult();
  }
    public function getObjectifProdByFranchiseMonth($userId, $month=null)
  {
$qb = $this->createQueryBuilder('a')
				->join('a.objectif', 'c')
				->where('a.month LIKE :month')
				->andWhere('c.utilisateur = :user')
				->setParameters(array(
					    'user' => $userId,
					    'month'  => $month,
					))
                ->orderBy('a.id', 'DESC');


    return $qb->getQuery()
              ->getResult();
  }
}


