<?php

namespace MyApp\ApBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifRepository extends EntityRepository
{
    
public function getObjectifProdByFranchise($user)
  {
 
$qb = $this->createQueryBuilder('a')
                ->orderBy('a.id', 'DESC');

    return $qb->getQuery()
              ->getResult();
  }
}


