<?php

namespace Proxies\__CG__\MyApp\ApBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Client extends \MyApp\ApBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setPrenom($prenom)
    {
        $this->__load();
        return parent::setPrenom($prenom);
    }

    public function getPrenom()
    {
        $this->__load();
        return parent::getPrenom();
    }

    public function setNumber($number)
    {
        $this->__load();
        return parent::setNumber($number);
    }

    public function getNumber()
    {
        $this->__load();
        return parent::getNumber();
    }

    public function setStreet($street)
    {
        $this->__load();
        return parent::setStreet($street);
    }

    public function getStreet()
    {
        $this->__load();
        return parent::getStreet();
    }

    public function setPhoneNumber($phoneNumber)
    {
        $this->__load();
        return parent::setPhoneNumber($phoneNumber);
    }

    public function getPhoneNumber()
    {
        $this->__load();
        return parent::getPhoneNumber();
    }

    public function addTitles(\MyApp\ApBundle\Entity\Titles $titles)
    {
        $this->__load();
        return parent::addTitles($titles);
    }

    public function getTitles()
    {
        $this->__load();
        return parent::getTitles();
    }

    public function setPc($pc)
    {
        $this->__load();
        return parent::setPc($pc);
    }

    public function getPc()
    {
        $this->__load();
        return parent::getPc();
    }

    public function setService(\MyApp\ApBundle\Entity\Service $service)
    {
        $this->__load();
        return parent::setService($service);
    }

    public function getService()
    {
        $this->__load();
        return parent::getService();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setUpdated($updated)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setCity(\MyApp\ApBundle\Entity\City $city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setDeskComment(\MyApp\ApBundle\Entity\Note $notes)
    {
        $this->__load();
        return parent::setDeskComment($notes);
    }

    public function setNote(\MyApp\ApBundle\Entity\Note $note)
    {
        $this->__load();
        return parent::setNote($note);
    }

    public function getNote()
    {
        $this->__load();
        return parent::getNote();
    }

    public function addNote(\MyApp\ApBundle\Entity\Note $note)
    {
        $this->__load();
        return parent::addNote($note);
    }

    public function setUser($user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function addContrat(\MyApp\ApBundle\Entity\Contrat $contrat)
    {
        $this->__load();
        return parent::addContrat($contrat);
    }

    public function getContrat()
    {
        $this->__load();
        return parent::getContrat();
    }

    public function setAncien($ancien)
    {
        $this->__load();
        return parent::setAncien($ancien);
    }

    public function getAncien()
    {
        $this->__load();
        return parent::getAncien();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setHeure($heure)
    {
        $this->__load();
        return parent::setHeure($heure);
    }

    public function getHeure()
    {
        $this->__load();
        return parent::getHeure();
    }

    public function setEtat($etat)
    {
        $this->__load();
        return parent::setEtat($etat);
    }

    public function getEtat()
    {
        $this->__load();
        return parent::getEtat();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setDateTable(\MyApp\ApBundle\Entity\DateTable $dateTable)
    {
        $this->__load();
        return parent::setDateTable($dateTable);
    }

    public function getDateTable()
    {
        $this->__load();
        return parent::getDateTable();
    }

    public function setPhoneNumberCell($phoneNumberCell)
    {
        $this->__load();
        return parent::setPhoneNumberCell($phoneNumberCell);
    }

    public function getPhoneNumberCell()
    {
        $this->__load();
        return parent::getPhoneNumberCell();
    }

    public function setLat($lat)
    {
        $this->__load();
        return parent::setLat($lat);
    }

    public function getLat()
    {
        $this->__load();
        return parent::getLat();
    }

    public function setLng($lng)
    {
        $this->__load();
        return parent::setLng($lng);
    }

    public function getLng()
    {
        $this->__load();
        return parent::getLng();
    }

    public function setFlag($flag)
    {
        $this->__load();
        return parent::setFlag($flag);
    }

    public function getFlag()
    {
        $this->__load();
        return parent::getFlag();
    }

    public function removeNote(\MyApp\ApBundle\Entity\Note $note)
    {
        $this->__load();
        return parent::removeNote($note);
    }

    public function removeContrat(\MyApp\ApBundle\Entity\Contrat $contrat)
    {
        $this->__load();
        return parent::removeContrat($contrat);
    }

    public function addTitle(\MyApp\ApBundle\Entity\Titles $titles)
    {
        $this->__load();
        return parent::addTitle($titles);
    }

    public function removeTitle(\MyApp\ApBundle\Entity\Titles $titles)
    {
        $this->__load();
        return parent::removeTitle($titles);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'user', 'ancien', 'nom', 'prenom', 'number', 'street', 'pc', 'lat', 'lng', 'phoneNumber', 'phoneNumberCell', 'etat', 'flag', 'email', 'date', 'heure', 'created', 'updated', 'city', 'service', 'note', 'dateTable', 'contrat', 'titles');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}