<?php

namespace Proxies\__CG__\MyApp\ApBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Contrat extends \MyApp\ApBundle\Entity\Contrat implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNumero($numero)
    {
        $this->__load();
        return parent::setNumero($numero);
    }

    public function getNumero()
    {
        $this->__load();
        return parent::getNumero();
    }

    public function addClientService(\MyApp\ApBundle\Entity\ClientService $clientService)
    {
        $this->__load();
        return parent::addClientService($clientService);
    }

    public function getClientService()
    {
        $this->__load();
        return parent::getClientService();
    }

    public function removeGroup($clientService)
    {
        $this->__load();
        return parent::removeGroup($clientService);
    }

    public function setClient(\MyApp\ApBundle\Entity\Client $client)
    {
        $this->__load();
        return parent::setClient($client);
    }

    public function getClient()
    {
        $this->__load();
        return parent::getClient();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setUpdated($updated)
    {
        $this->__load();
        return parent::setUpdated($updated);
    }

    public function getUpdated()
    {
        $this->__load();
        return parent::getUpdated();
    }

    public function setProduction(\MyApp\ApBundle\Entity\Production $production)
    {
        $this->__load();
        return parent::setProduction($production);
    }

    public function getProduction()
    {
        $this->__load();
        return parent::getProduction();
    }

    public function setContratEstimation($contratEstimation)
    {
        $this->__load();
        return parent::setContratEstimation($contratEstimation);
    }

    public function getContratEstimation()
    {
        $this->__load();
        return parent::getContratEstimation();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setDateDepot($dateDepot)
    {
        $this->__load();
        return parent::setDateDepot($dateDepot);
    }

    public function getDateDepot()
    {
        $this->__load();
        return parent::getDateDepot();
    }

    public function setDepot($depot)
    {
        $this->__load();
        return parent::setDepot($depot);
    }

    public function getDepot()
    {
        $this->__load();
        return parent::getDepot();
    }

    public function setDateTable(\MyApp\ApBundle\Entity\DateTable $dateTable = NULL)
    {
        $this->__load();
        return parent::setDateTable($dateTable);
    }

    public function getDateTable()
    {
        $this->__load();
        return parent::getDateTable();
    }

    public function removeClientService(\MyApp\ApBundle\Entity\ClientService $clientService)
    {
        $this->__load();
        return parent::removeClientService($clientService);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'numero', 'contratEstimation', 'date', 'dateDepot', 'depot', 'created', 'updated', 'clientService', 'client', 'dateTable', 'production');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}