parameters:
#    front_end_super.example.class: FrontEnd\SuperBundle\Example

services:
#    front_end_super.example:
#        class: %front_end_super.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
